import {getTranslations} from "@/lib/i18n/server";
import {dateLocale,enumLabel} from "@/lib/i18n";
import Link from "next/link";import {redirect} from "next/navigation";import {serverSupabase} from "@/lib/supabase/server";import {staffPageSchema} from "@/lib/validation";import {AssignmentForm} from "./action-forms";
type CaseRow={id:string;case_number:number;category:string;city:string;urgency:string;status:string;created_at:string;coordinator_id?:string|null;coordinator_name?:string|null};
export default async function StaffCases({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const {t,locale}=await getTranslations();const raw=await searchParams,pageResult=staffPageSchema.safeParse(raw.page),page=pageResult.success?pageResult.data:1,limit=20,offset=(page-1)*limit,s=await serverSupabase(),{data:{user}}=await s.auth.getUser();if(!user)redirect("/auth");const {data:staffRole}=await s.rpc("current_staff_role");if(!staffRole)redirect("/cabinet");const isAdmin=staffRole==="ADMIN";let rows:CaseRow[]=[];let coordinators:{id:string;display_name:string}[]=[];if(isAdmin){const [queue,staff]=await Promise.all([s.rpc("assignment_queue",{queue_limit:limit+1,queue_offset:offset}),s.rpc("staff_coordinators",{coordinator_limit:100})]);if(queue.error||staff.error)redirect("/cabinet");rows=(queue.data??[]) as CaseRow[];coordinators=(staff.data??[]) as typeof coordinators}else{const assigned=await s.rpc("coordinator_cases",{case_limit:limit+1,case_offset:offset});if(assigned.error)redirect("/cabinet");rows=(assigned.data??[]) as CaseRow[]}const hasNext=rows.length>limit;rows=rows.slice(0,limit);return <section className="container section"><nav className="nav" aria-label={t("Рабочее место")}><Link href="/cabinet">{t("Кабинет")}</Link><strong>{isAdmin?t("Очередь обращений"):t("Назначенные обращения")}</strong>{isAdmin && (
  <>
    <Link href="/staff/reports">
      {t("Жалобы")}
    </Link>

    <Link href="/staff/volunteers">
      {t("Предложения помощи")}
    </Link>
  </>
)}</nav><h1>{isAdmin?t("Очередь обращений"):t("Мои обращения в работе")}</h1><p className="muted">{isAdmin?t("Только сведения для маршрутизации: содержание и переписка администратору автоматически не открываются."):t("Откройте приватную карточку, чтобы продолжить чат или изменить статус.")}</p><div className="grid">{rows.length?rows.map(r=><article className="card" key={r.id}><div className="case-heading"><div><h2>{t("Обращение №")} {r.case_number}</h2><p>{enumLabel(t,r.category)} · {r.city}</p><p><strong>{enumLabel(t,r.urgency)}</strong> · {enumLabel(t,r.status)} · <time dateTime={r.created_at}>{new Date(r.created_at).toLocaleDateString(dateLocale(locale))}</time></p>{isAdmin&&<p>{t("Координатор:")} {r.coordinator_name??t("не назначен")}</p>}</div>{!isAdmin&&<Link className="btn" href={`/cabinet/requests/${r.id}`}>{t("Открыть карточку")}</Link>}</div>{isAdmin&&<AssignmentForm caseId={r.id} currentCoordinatorId={r.coordinator_id??null} coordinators={coordinators}/>}</article>):<div className="card">{isAdmin?t("Очередь пуста."):t("Назначенных обращений пока нет.")}</div>}</div><nav className="pagination" aria-label={t("Страницы")}>{page>1&&<Link className="btn secondary" href={`/staff/cases?page=${page-1}`}>{t("Назад")}</Link>}<span>{t("Страница")} {page}</span>{hasNext&&<Link className="btn secondary" href={`/staff/cases?page=${page+1}`}>{t("Далее")}</Link>}</nav></section>}
