\set ON_ERROR_STOP on
begin;
select plan(39);
select has_table('public','help_requests','schema reproduced');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.help_requests'::regclass),'help_requests: RLS enabled');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.messages'::regclass),'messages: RLS enabled');
select has_index('public','service_locations','service_locations_geo_idx','geo index exists');
select ok(not has_function_privilege('anon','public.bootstrap_first_admin(uuid)','EXECUTE') and not has_function_privilege('authenticated','public.bootstrap_first_admin(uuid)','EXECUTE'),'bootstrap unavailable via API');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.profiles'::regclass),'profiles: RLS enabled');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.case_assignments'::regclass),'case_assignments: RLS enabled');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.consents'::regclass),'consents: RLS enabled');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.audit_events'::regclass),'audit_events: RLS enabled');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.volunteer_offers'::regclass),'volunteer offers use RLS');
select ok(not has_table_privilege('authenticated','public.volunteer_offers','INSERT'),'offer identity and consent cannot bypass the atomic RPC');
select ok(has_function_privilege('authenticated','public.create_volunteer_offer(jsonb,text)','EXECUTE') and not has_function_privilege('anon','public.create_volunteer_offer(jsonb,text)','EXECUTE'),'offer creation requires a user JWT');
select ok(has_function_privilege('authenticated','public.moderate_volunteer_offer(uuid,public.review_status,text)','EXECUTE') and not has_function_privilege('anon','public.moderate_volunteer_offer(uuid,public.review_status,text)','EXECUTE'),'offer moderation requires a user JWT and checks admin internally');
select ok(has_function_privilege('authenticated','public.send_message(uuid,text,uuid)','EXECUTE') and not has_function_privilege('anon','public.send_message(uuid,text,uuid)','EXECUTE'),'message RPC is authenticated only');
select ok(has_function_privilege('authenticated','public.assign_case(uuid,uuid,text)','EXECUTE') and not has_function_privilege('anon','public.assign_case(uuid,uuid,text)','EXECUTE'),'assignment RPC is authenticated only and enforces admin internally');
select ok(not has_function_privilege('anon','public.set_staff_role(uuid,public.staff_role,boolean,text)','EXECUTE') and has_function_privilege('authenticated','public.set_staff_role(uuid,public.staff_role,boolean,text)','EXECUTE'),'staff-role RPC is authenticated only');
select ok(not has_function_privilege('anon','public.create_help_request(jsonb,text)','EXECUTE') and has_function_privilege('authenticated','public.create_help_request(jsonb,text)','EXECUTE'),'request RPC is authenticated only');
select ok(not has_function_privilege('anon','public.assignment_queue(integer,integer)','EXECUTE') and has_function_privilege('authenticated','public.assignment_queue(integer,integer)','EXECUTE'),'queue RPC is authenticated only');
select ok(not has_function_privilege('anon','public.staff_coordinators(integer)','EXECUTE') and has_function_privilege('authenticated','public.staff_coordinators(integer)','EXECUTE'),'coordinator directory is authenticated and checks admin internally');
select ok(not has_function_privilege('anon','public.coordinator_cases(integer,integer)','EXECUTE') and has_function_privilege('authenticated','public.coordinator_cases(integer,integer)','EXECUTE'),'coordinator case list requires a user JWT');
select ok(not has_function_privilege('anon','public.current_staff_role()','EXECUTE') and has_function_privilege('authenticated','public.current_staff_role()','EXECUTE'),'current staff role requires a user JWT');
select ok(not has_function_privilege('anon','public.enforce_message()','EXECUTE') and not has_function_privilege('authenticated','public.enforce_message()','EXECUTE'),'message trigger is not API callable');
select ok(not has_function_privilege('anon','public.enforce_catalog_review()','EXECUTE') and not has_function_privilege('authenticated','public.enforce_catalog_review()','EXECUTE'),'catalog trigger is not API callable');
select ok(has_function_privilege('anon','public.nearby_service_locations(double precision,double precision,integer,integer,integer)','EXECUTE') and has_function_privilege('authenticated','public.nearby_service_locations(double precision,double precision,integer,integer,integer)','EXECUTE'),'public geo RPC remains callable');
create function public.pgtap_default_privilege_probe() returns boolean language sql as $$select true$$;
select ok(not has_function_privilege('anon','public.pgtap_default_privilege_probe()','EXECUTE') and not has_function_privilege('authenticated','public.pgtap_default_privilege_probe()','EXECUTE'),'new functions do not acquire API execution by default');
select isnt((select relreplident from pg_class where oid='public.messages'::regclass),'f','messages do not expose FULL old rows on DELETE');
select results_eq($$select count(*)::bigint from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages'$$,array[1::bigint],'messages publication configured exactly once');
select ok(to_regclass('public.specialist_profiles') is null,'specialist profiles are removed from Mercy');
select ok(to_regclass('public.qualification_documents') is null,'qualification documents are removed from Mercy');
select ok(to_regclass('public.published_specialists') is null,'published specialist projection is removed from Mercy');
select ok(to_regprocedure('public.search_specialists(text,text,text,text,boolean,integer,integer)') is null,'specialist search RPC is removed from Mercy');
select ok(to_regprocedure('public.save_specialist_profile(jsonb)') is null,'specialist write RPC is removed from Mercy');
select has_table('public','help_request_responses','direct help responses exist');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.help_request_responses'::regclass),'help responses use RLS');
select ok(not has_table_privilege('authenticated','public.help_request_responses','INSERT'),'response identity and consent cannot bypass RPC');
select ok(has_function_privilege('authenticated','public.respond_to_help_request(uuid,jsonb,text)','EXECUTE') and not has_function_privilege('anon','public.respond_to_help_request(uuid,jsonb,text)','EXECUTE'),'request response requires authenticated user');
select has_table('public','feedback_messages','feedback inbox exists');
select ok(not has_table_privilege('anon','public.feedback_messages','SELECT') and not has_table_privilege('authenticated','public.feedback_messages','SELECT'),'feedback inbox is not directly readable');
select ok(has_function_privilege('anon','public.submit_feedback(text,text,text)','EXECUTE') and has_function_privilege('authenticated','public.submit_feedback(text,text,text)','EXECUTE'),'feedback submission is available before and after login');
select * from finish();
rollback;
